mgechev/javascript-algorithms

- doc-config.json
- gulpfile.js
- package.json
> gulp jsdoc command fixed, now @param and @return works

- .gitignore
- doc-config.json
- readme.md
- src/graphs/shortest-path/bellman-ford.js
- src/graphs/spanning-trees/prim.js
Changes:
* fixed readme
* fixed bellman-ford syntax and jsdoc
* added prim's jsdoc
> 2nd documentation pack

- src/data-structures/red-black-tree.js
So, now all data-structures (but without suffix-tree) has jsdoc.
As far as I understand suffix-tree is not finished yet.
> Red-black tree documentation

- .gitignore
- gulpfile.js
- src/primes/is-prime.js
- src/primes/prime-factor-tree.js
- src/primes/sieve-of-eratosthenes.js
- test/primes/is-prime.spec.js
- test/primes/prime-factor-tree.spec.js
- test/primes/sieve-of-eratosthenes.spec.js
Hi guys,
I discovered that basic algorithms for prime numbers is missing.
So I added following:
- (75f6d51) Sieve of Eratosthenes - simple, ancient algorithm for finding all prime numbers up to any given limit;
- (edc6634) Is Prime - advanced (optimised) method for checking if provided number is prime;
- (2b053e9) Prime Factor Tree - will return list of all primes for provided number;
- (3b9d5ed) Some advanced algorithms tests for isPrime and SieveOfEratosthenes.
Cheers!
> Added base algorithms for Prime numbers

- doc-config.json
- src/primes/is-prime.js
- src/primes/prime-factor-tree.js
- src/primes/sieve-of-eratosthenes.js
Hi,
I updated jsdoc for Primes.
Cheers!
> Upated jsdoc for Primes

- src/others/hanoi.js
> Hanoi jsdoc

- doc-config.json
- src/others/hanoi.js
- src/searching/binarysearch/binarysearch.js
- src/searching/binarysearch/recursive-binarysearch.js
> Doc pack10

- src/searching/knuth-morris-pratt.js
- src/searching/longest-increasing-subsequence.js
- src/searching/maximum-subarray-divide-and-conquer.js
- src/searching/maximum-subarray.js
- src/searching/quickselect.js
> Doc pack11

- doc-config.json
- src/sets/quickfind.js
- src/sets/quickunion.js
- src/sets/weightquickunion.js
> Doc pack12

- doc-config.json
- src/shuffle/fisheryates.js
- src/shuffle/richarddurstenfeld.js
- src/sorting/3-way-string-quicksort.js
- src/sorting/bubblesort.js
- src/sorting/bucketsort.js
shuffle, 3-way-string-quicksort, bubblesort, bucketsort jsdoc
> Doc pack13

- src/sorting/countingsort.js
- src/sorting/heapsort.js
- src/sorting/insertion-binary-sort.js
- src/sorting/insertionsort.js
- src/sorting/lsd.js
- src/sorting/mergesort.js
- src/sorting/msd.js
- src/sorting/quicksort-middle.js
- src/sorting/recursive-insertionsort.js
- src/sorting/selectionsort.js
- src/sorting/shellsort.js
Hey @mgechev,
this is doc pack with sorting algorithms.
It looks like now we have documentation for all algorithms!
> Doc pack14

- src/searching/binarysearch.js
- test/searching/binarysearch.spec.js
If an element is not found, return `-x - 1` where `x` is the index into which the element should be inserted
Closes #36
> Adds key function to binarysearch.js

- src/sorting/mergesort.js
Adds optional `start` and `end` parameters to `mergeSort`
Exposes `mergeSort.merge`
Updates documentation
> Refactors src/sorting/mergesort.js

- src/sorting/mergesort.js
> Fixes jsdoc for mergesort

- src/sorting/oddeven-sort.js
- test/sorting/oddeven-sort.spec.js
Implementation of Odd even sort algorithm with O(N^2) complexity
> Added odd even sort algorithm

- src/data-structures/binary-search-tree.js
- test/data-structures/binary-search-tree.spec.js
Issue here:
https://github.com/mgechev/javascript-algorithms/issues/46
Fix:
```js
if (node._parent !== null) { // change - make sure parent is not null before replacing child
if (node._left) {
this._replaceChild(node._parent, node, node._left);
} else if (node._right) {
this._replaceChild(node._parent, node, node._right);
} else {
this._replaceChild(node._parent, node, null);
}
}else {
this._root = null; // if the parent is null, we are removing root, therefore assign null to root
}
```
Also added several basic tests.
And fixes some of the method comments so doc generation is correct.
> bst remove root node fix. bst specs.

- src/compression/LZW/LZW.js
Lempel–Ziv–Welch (LZW) is a universal lossless data compression
algorithm. It is an improved implementation of the LZ78 algorithm.
> LZW Encoding/Decoding

- src/others/fibonacci.js
An algorithm to find the nth number in the fibonacci’s sequence
> Fibonacci algorithm

- src/data-structures/hash-table.js
A hash table is a data structure used to implement an associative
array, that can map keys to values. A hash table uses a hash function
to compute an index into an array of buckets or slots, from which the
correct value can be found. The idea is to access a value in O(1).
> Hash Table data structure

- data-structures_hash-table.js.html
- module-data-structures_hash-table.Hashtable.html
- module-data-structures_hash-table.Node.html
Submitting a PR for review since I sort of had to hack around (thanks to https://github.com/mgechev/javascript-algorithms/issues/77) with jsdoc to get the docs generated.
> Update Hash table docs.

- src/primes/is-prime.js
- src/shuffle/fisheryates.js
Hi,
I just improved the prime check and the Fisher Yates shuffle algorithm. Sorry for pulling both in one request. If you want to accept just one, I can split them up.
The implementation of the Richard Durstenfeld algo is also not correct, but maybe you can drop it, as it is just a modified Fisher Yates.
Robert
> Improved prime check and Fisher Yates

- src/sorting/radixsort.js
- test/sorting/radixsort.spec.js
A non comparative, stable integer sorting algorithm.
> Add radix sort algorithm

- src/others/levenshtein-distance.js
- test/others/levenshtein-distance.spec.js
Replaced the recursive implementation with iterative, utilizing the memoization technique.
> Optimized Levenshtein distance algorithm and added unit tests.

- src/sorting/radixsort.js
1) array.length -> size
2) auxiliary typo
> Sorting radixsort

- .travis.yml
- src/data-structures/size-balanced-tree.js
- test/data-structures/size-balanced-tree.spec.js
This makes we can using this tree do binary-search /insert/delete after all.
This is closing issue #88
> Create size balanced tree for getting the binary tree act like a Javascript Array.

- src/others/min-coins-change.js
Hi
Quick PR. 
See more: http://usejsdoc.org/tags-inline-link.html
Thnaks in advance.
> Make link clickable

- src/searching/longest-common-subsequence.js
- src/searching/longest-increasing-subsequence.js
- test/searching/longest-common-subsequence.spec.js
- test/searching/longest-increasing-subsequence.spec.js
#111 Renamed longest-subsequence, implemented longest common subsequence.
> #111 Longest common subsequence

- src/data-structures/red-black-tree.js
- test/data-structures/red-black-tree.spec.js
Level Order Traversal **Enhancement** using queue for Red-Black Tree.
Reference - [http://www.geeksforgeeks.org/level-order-tree-traversal/](url)
> Level Order Traversal for red black tree using queue.

- src/graphs/spanning-trees/kruskal.js
- test/graphs/spanning-trees/kruskal.spec.js
This repo is really cool and I would like to contribute 🎉 . I added an implementation of [Kruskal's MST algorithm](https://en.wikipedia.org/wiki/Kruskal%27s_algorithm) and one of the examples from Wikipedia as test case. I tried to mimic the module style of existing algorithms, let me know if I should change the structure or if anything else is missing.
I am not sure how to add documentation for the website, but am willing to help with it if you tell me what to do.
> Add Kruskal's algorithm for minimal spanning tree

- .travis.yml
- package.json
- readme.md
Update readme for test command and add npm build script to use local gulp.
> update build and test scripts

- src/data-structures/bloomfilter.js
- test/data-structures/bloomfilter.spec.js
Changes:
- add helper data structure bitmap implementation
- implement the bloomfilter using the bitmap. 
- necessary unit test for the bloomfilter
Note:
Bloom filter is completely probabilistic. There is a chance that the test case will fail, but it not likely to happen since the threshold I set in the test case is quite high
> [feature] add probablistic data structure bloomfilter

- .eslintrc.json
- package-lock.json
- src/combinatorics/variations-repetition.js
- src/compression/runlength/runlength.js
- src/graphics/graham.js
- src/others/min-coins-change.js
- src/searching/recursive-binarysearch.js
- src/sorting/quicksort-middle.js
- src/sorting/quicksort.js
- test/graphics/grapham.spec.js
PR contains the following changes:
* Fix spelling errors
* Fix `eslint` errors
* Remove duplicates in `eslintrc`
> Several minor fixes

- src/searching/interpolation-search.js
I also updated the complexity of the `interpolation` search.
Closes #169
> Fix typo in interpolation search algorithm

- gulpfile.js
- package-lock.json
- package.json
- src/others/minimax.js
- yarn.lock
Hey I saw your build was failing in CI, It was also failing locally. I updated the Gulp dependency and refactored the gulp.js file a bit. 
Additionally there were some linting errors which failed the build so I fixed those as well
> [gulpUpdate]: Updated Gulp dependency to fix build failure

- src/others/fibonacci.js
- src/others/fibonacciMemory.js
- src/searching/linearSearch.js
- test/others/fibonacciMemory.spec.js
Fixe linter errors when building
> :rotating_light: Fix linter errors
